Long-running workers on Android devices
fluttercommunity/flutter_workmanager pull request #573
Opened 2024-10-21 13:41 UTC by wagner1343

2024-10-21 14:29 UTC, wagner1343 commented
@ened I Kindly ask for your input on this.

2024-11-07 17:20 UTC, absar requested changes
Thank you for building these features. I have left some comments

2024-11-07 17:20 UTC, absar commented on workmanager/lib/src/workmanager.dart
> -    /// Only supported on Android.
Probably use default dart formatting `2-space indenting`, so that it does not change the code which is not modified

2024-11-07 17:20 UTC, absar commented on workmanager/lib/src/workmanager.dart
> +    required this.notificationDescription});
Add a trailing-comma and format again, to be consistent

2024-11-07 17:20 UTC, absar commented on workmanager/lib/workmanager.dart
>  export 'src/workmanager.dart' show Workmanager;
Instead do: export 'src/workmanager.dart' show Workmanager, SetForegroundOptions, etc;

2024-11-07 17:20 UTC, absar commented on workmanager/android/src/main/kotlin/dev/fluttercommunity/workmanager/WorkmanagerCallHandler.kt
> +import android.content.pm.ServiceInfo
Is the import used?

2024-11-07 17:20 UTC, absar commented on workmanager/android/src/main/kotlin/dev/fluttercommunity/workmanager/Extractor.kt
> -                        extractBackoffPolicyConfigFromCall(
@ened is this formatting ok, or it should be reverted. To not add unncessary changed lines and simplify reviews single formatting should be used

2024-11-07 17:23 UTC, absar requested changes

2026-08-02 09:49 UTC, ened commented
## Takeover notice

Thanks for building this, @wagner1343 — the foreground-service direction was exactly right, and it's been a useful reference for the final design.

This PR has been taken over and reimplemented against the current `main` (the 0.9.x architecture: Pigeon platform interface, `WorkmanagerPlugin`, typed requests). The branch was too stale to rebase cleanly, so the new implementation landed in:

**#698 — feat(android): long-running workers via foreground service (fixes #573)**

What changed compared to this branch:

- Registration-time API instead of a runtime `setForeground` call: `registerOneOffTask` / `registerPeriodicTask` now accept a `foregroundServiceConfig` (notification title/text/channel, notification id, `dataSync`/`shortService` foreground service type) with sane defaults — no separate worker-thread hack.
- The config travels through the Pigeon platform contract and the WorkRequest input data, and the worker calls WorkManager's `setForegroundAsync` as soon as it starts.
- Android 14+ requirements are handled: the plugin manifest declares `dataSync|shortService` on WorkManager's `SystemForegroundService` plus the required type permissions, so no native setup is needed.
- Platform-interface unit tests and native JVM tests were added; docs updated.

Closing this PR in favor of #698. Thanks again for the original work!

2026-08-02 09:49 UTC, ened commented
Superseded by #698 — long-running workers now land as foreground-service support on the current architecture.

2026-08-02 09:49 UTC, closed without merging